services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      POSTGRES_URL: ${POSTGRES_DB_URL}
      PGPORT: 5050
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5050"
    ports:
      - "5050:5432"
    command: -p 5050

  auth-service:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  db-data:
    driver: local